### ISSUE TITLE
Little weirdness with Settings button

### ISSUE THREAD

**Issue by bambibrewer** [BirdBrainTechnologies/flutter-kindle-sttr2#78]
The settings work great in GlowGrid! I am really pleased. However, the Settings button itself is visible on the Addition and Subtraction main screens (which makes sense), but when you tap on it, it doesn't actually do anything.

Also, can we disable the Settings button in CubeTower? There are no teacher settings right now, and if you tap it from the home screen, you bring up what is presumably a debugging screen, but you can't get back to the app without swiping out.

**Comment by tasota** [comment]
Sorry, i did not see this until now. I can disable settings in CubeTower.

For the settings buttons elsewhere, do we want them to navigate to settings or did we want to just omit them? I personally find having the settings button on each math section a bit confusing, especially since these settings only exit for 3 out of 5 operations.

**Comment by bambibrewer** [comment]
I agree that it does not make sense to have the settings button on the division options. Is it possible to have it only on those sections that have settings? I can see being on the addition screen and wanting to adjust the settings for addition.
